
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.22631 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "web_build/_deps/raylib-src/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "web_build/_deps/raylib-src/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "web_build/_deps/raylib-src/CMakeLists.txt:29 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-ueu3y1"
      binary: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-ueu3y1"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/_deps/raylib-src/cmake"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_CHAINLOAD_TOOLCHAIN_FILE: "C:/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
      VCPKG_TARGET_TRIPLET: "wasm32-emscripten"
      Z_VCPKG_ROOT_DIR: "C:/DEV/vcpkg"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-ueu3y1'
        
        Run Build Command(s): C:/Users/thoma/scoop/shims/ninja.exe -v cmTC_5488e
        [1/2] C:\\emsdk\\upstream\\emscripten\\emcc.bat -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_5488e.dir/src.c.o -MF CMakeFiles\\cmTC_5488e.dir\\src.c.o.d -o CMakeFiles/cmTC_5488e.dir/src.c.o -c C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-ueu3y1/src.c
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\emsdk\\upstream\\emscripten\\emcc.bat   CMakeFiles/cmTC_5488e.dir/src.c.o -o cmTC_5488e.js   && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CheckCSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/FindThreads.cmake:97 (CHECK_C_SOURCE_COMPILES)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "C:/DEV/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "web_build/_deps/raylib-src/src/external/glfw/CMakeLists.txt:64 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-br3u08"
      binary: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-br3u08"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_C_FLAGS: "-fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith "
      CMAKE_MODULE_PATH: "C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/_deps/raylib-src/cmake;C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/_deps/raylib-src/src/external/glfw/CMake/modules"
      VCPKG_APPLOCAL_DEPS: "ON"
      VCPKG_CHAINLOAD_TOOLCHAIN_FILE: "C:/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
      VCPKG_TARGET_TRIPLET: "wasm32-emscripten"
      Z_VCPKG_ROOT_DIR: "C:/DEV/vcpkg"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-br3u08'
        
        Run Build Command(s): C:/Users/thoma/scoop/shims/ninja.exe -v cmTC_7c6e6
        [1/2] C:\\emsdk\\upstream\\emscripten\\emcc.bat -DCMAKE_HAVE_LIBC_PTHREAD  -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_7c6e6.dir/src.c.o -MF CMakeFiles\\cmTC_7c6e6.dir\\src.c.o.d -o CMakeFiles/cmTC_7c6e6.dir/src.c.o -c C:/Users/thoma/Documents/GitHub/raylib-game-template-main/web_build/CMakeFiles/CMakeScratch/TryCompile-br3u08/src.c
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && C:\\emsdk\\upstream\\emscripten\\emcc.bat -fno-strict-aliasing -Werror=implicit-function-declaration -Werror=pointer-arith  CMakeFiles/cmTC_7c6e6.dir/src.c.o -o cmTC_7c6e6.js   && cd ."
        
      exitCode: 0
...
